[package]
name = "lsql"
version = "0.1.0"
edition = "2021"
exclude = [".github/**", "docs/**", "media/**", "scripts/**"]
readme = "README.md"

[dependencies]
walkdir = "2.5.0"
chrono = "0.4.38"
comfy-table = "7.1.1"
antlr-rust = { version = "0.3.0-beta" }